/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCartRouteImport } from './routes/api/cart'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiTaxRouteImport } from './routes/api/tax'
import { Route as ApiAgentSplatRouteImport } from './routes/api/agent/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartRoute = ApiCartRouteImport.update({
  id: '/api/cart',
  path: '/api/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTaxRoute = ApiTaxRouteImport.update({
  id: '/api/tax',
  path: '/api/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSplatRoute = ApiAgentSplatRouteImport.update({
  id: '/api/agent/$',
  path: '/api/agent/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cart': typeof ApiCartRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/tax': typeof ApiTaxRoute
  '/api/agent/$': typeof ApiAgentSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cart': typeof ApiCartRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/tax': typeof ApiTaxRoute
  '/api/agent/$': typeof ApiAgentSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cart': typeof ApiCartRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/tax': typeof ApiTaxRoute
  '/api/agent/$': typeof ApiAgentSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/cart' | '/api/checkout' | '/api/tax' | '/api/agent/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/cart' | '/api/checkout' | '/api/tax' | '/api/agent/$'
  id:
    | '__root__'
    | '/'
    | '/api/cart'
    | '/api/checkout'
    | '/api/tax'
    | '/api/agent/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCartRoute: typeof ApiCartRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiTaxRoute: typeof ApiTaxRoute
  ApiAgentSplatRoute: typeof ApiAgentSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart': {
      id: '/api/cart'
      path: '/api/cart'
      fullPath: '/api/cart'
      preLoaderRoute: typeof ApiCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tax': {
      id: '/api/tax'
      path: '/api/tax'
      fullPath: '/api/tax'
      preLoaderRoute: typeof ApiTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/$': {
      id: '/api/agent/$'
      path: '/api/agent/$'
      fullPath: '/api/agent/$'
      preLoaderRoute: typeof ApiAgentSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCartRoute: ApiCartRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiTaxRoute: ApiTaxRoute,
  ApiAgentSplatRoute: ApiAgentSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
